#!/usr/bin/env node
// scripts/build-rules.js
//
// Builds the Firestore security rules for ONE workspace's database from the committed
// firestore.rules, so there is a single rules file to maintain.
//
// WHY: the rules run in the browser, not only on the server. Several rules trust "any
// signed-in user" (`request.auth != null`). With one database per client and one sign-in pool
// per client, that has to become "any user signed in to THIS workspace's pool" — otherwise a
// user of one client could point the browser SDK at another client's database. Rules cannot
// know which workspace they are deployed to, so the workspace is baked in at build time.
//
// WHAT: every `request.auth != null` in the rules becomes `inThisWorkspace()`, a helper added
// to the output:
//   --tenant <id>   inThisWorkspace() = signed in AND token.firebase.tenant == <id>
//   --default       inThisWorkspace() = signed in AND the token has NO tenant
//                   (the default workspace uses the project-level pool; once any tenant
//                   exists its users must not be able to reach the default database either)
// Nothing else is changed. Comments are left alone, and the output is checked to have the
// same structure as the input (same rules, same braces) before it is returned.
//
// Usage:
//   node scripts/build-rules.js --default            [--out file]
//   node scripts/build-rules.js --tenant <tenantId>  [--out file]
//
// IMPORTANT: firestore.rules itself is deliberately NOT changed by this, because merging a
// change to it deploys it to the live database (deploy-firestore-rules.yml). Test generated
// rules in the Firebase Emulator before deploying them; see docs/MULTI-WORKSPACE.md.

const fs = require('fs');
const path = require('path');

const TENANT_RE = /^[A-Za-z0-9_-]{4,64}$/; // the id is written into the rules text, so keep it strict
const ANCHOR = /^([ \t]*)match \/databases\/\{database\}\/documents \{[ \t]*$/m;

// Splits a line into [code, trailingComment] at the first `//` that is not inside a string.
function splitComment(line) {
  let quote = null;
  for (let i = 0; i < line.length; i++) {
    const c = line[i];
    if (quote) { if (c === '\\') i++; else if (c === quote) quote = null; }
    else if (c === '"' || c === "'") quote = c;
    else if (c === '/' && line[i + 1] === '/') return [line.slice(0, i), line.slice(i)];
  }
  return [line, ''];
}

function buildRules(base, { tenantId = null, label = null } = {}) {
  if (tenantId !== null && !TENANT_RE.test(String(tenantId))) {
    throw new Error(`invalid tenant id ${JSON.stringify(tenantId)} (letters, digits, "_" and "-", 4-64 characters)`);
  }
  if (/inThisWorkspace\s*\(/.test(base)) throw new Error('input already contains inThisWorkspace(): build from the committed firestore.rules, not from generated output');
  const anchor = base.match(ANCHOR);
  if (!anchor) throw new Error('could not find "match /databases/{database}/documents {" in the rules');

  let replaced = 0;
  const lines = base.split('\n').map(line => {
    if (/^\s*\/\//.test(line)) return line; // full-line comment: untouched
    const [code, comment] = splitComment(line);
    const out = code.replace(/request\.auth\s*!=\s*null/g, () => { replaced++; return 'inThisWorkspace()'; });
    return out + comment;
  });
  if (!replaced) throw new Error('found no `request.auth != null` to replace — is this the right file?');

  const cond = tenantId === null
    ? "request.auth != null && !('tenant' in request.auth.token.firebase)"
    : `request.auth != null && request.auth.token.firebase.tenant == '${tenantId}'`;
  const indent = anchor[1] + '  ';
  const helper = [
    `${indent}// Added by scripts/build-rules.js — do not edit by hand.`,
    `${indent}// True only for a user signed in to THIS workspace's own sign-in pool.`,
    `${indent}function inThisWorkspace() {`,
    `${indent}  return ${cond};`,
    `${indent}}`,
    '',
  ];
  const at = lines.findIndex(l => ANCHOR.test(l));
  lines.splice(at + 1, 0, ...helper);

  const who = tenantId === null ? 'the DEFAULT workspace' : `workspace tenant ${tenantId}`;
  const header = [`// GENERATED by scripts/build-rules.js from firestore.rules for ${label || who}.`, '// Edit firestore.rules, not this file.', ''];
  const text = [...header, ...lines].join('\n');

  verifyStructure(base, text, replaced);
  return { text, replaced };
}

// The output must differ from the input ONLY by the helper and the substitutions.
function verifyStructure(base, out, replaced) {
  const count = (t, re) => (t.match(re) || []).length;
  const checks = [
    ['same number of allow statements', count(base, /^\s*allow\s/gm) === count(out, /^\s*allow\s/gm)],
    ['same number of match blocks', count(base, /^\s*match\s/gm) === count(out, /^\s*match\s/gm)],
    ['exactly one new function', count(base, /^\s*function\s/gm) + 1 === count(out, /^\s*function\s/gm)],
    ['balanced braces', count(out, /{/g) === count(out, /}/g) && count(base, /{/g) + 1 === count(out, /{/g)],
    ['balanced parentheses', count(out, /\(/g) === count(out, /\)/g)],
    ['no bare `request.auth != null` left outside the helper and comments',
      out.split('\n').filter(l => !/^\s*\/\//.test(l) && /request\.auth\s*!=\s*null/.test(splitComment(l)[0])).length === 1],
    ['every substitution is present', count(out, /inThisWorkspace\(\)/g) === replaced + 1 /* the helper's own declaration */],
  ];
  const bad = checks.filter(c => !c[1]).map(c => c[0]);
  if (bad.length) throw new Error('generated rules failed a structural check: ' + bad.join('; '));
}

module.exports = { buildRules, TENANT_RE };

if (require.main === module) {
  const args = process.argv.slice(2);
  const val = flag => { const i = args.indexOf(flag); return i >= 0 ? args[i + 1] : undefined; };
  const outFile = val('--out');
  try {
    let opts;
    if (args.includes('--default')) opts = { tenantId: null };
    else if (val('--tenant')) opts = { tenantId: val('--tenant') };
    else throw new Error('usage: build-rules.js --default | --tenant <tenantId>  [--out <file>]');
    const base = fs.readFileSync(path.resolve(__dirname, '../firestore.rules'), 'utf8');
    const { text, replaced } = buildRules(base, opts);
    if (outFile) { fs.writeFileSync(outFile, text); console.error(`wrote ${outFile} (${replaced} auth checks scoped to the workspace)`); }
    else process.stdout.write(text);
  } catch (e) { console.error('build-rules: ' + e.message); process.exit(1); }
}
