#!/usr/bin/env node
// scripts/test-rules.js
//
// The per-workspace rules generator (scripts/build-rules.js). It rewrites SECURITY RULES, so
// these tests pin down that the output differs from firestore.rules only where intended, and
// that a tenant id can never smuggle rules text into the output.
//
// What this CANNOT do: evaluate the rules. That needs the Firebase Emulator (see
// docs/MULTI-WORKSPACE.md); generated rules must be tried there before they are deployed.
//
// Usage: node scripts/test-rules.js   (or: npm test)

const fs = require('fs');
const path = require('path');
const { buildRules } = require('./build-rules');

let passed = 0, failed = 0;
function check(name, cond, detail) {
  if (cond) { passed++; console.log(`\x1b[32m✓\x1b[0m ${name}`); }
  else { failed++; console.log(`\x1b[31m✗ ${name}\x1b[0m${detail ? '\n  ' + String(detail).split('\n').join('\n  ') : ''}`); }
}
const throws = fn => { try { fn(); return null; } catch (e) { return e; } };

const BASE = fs.readFileSync(path.resolve(__dirname, '../firestore.rules'), 'utf8');
const code = t => t.split('\n').filter(l => !/^\s*\/\//.test(l));
const TENANT = 'acme-x1y2z';

// ── the committed rules are untouched ───────────────────────────────────────
check('firestore.rules itself is not generated output (it deploys to production on merge)', !/inThisWorkspace|GENERATED by/.test(BASE));
const anyUser = code(BASE).filter(l => /request\.auth\s*!=\s*null/.test(l)).length;
check(`the committed rules contain ${anyUser} \`request.auth != null\` checks to scope`, anyUser >= 10, `found ${anyUser}`);

// ── tenant build ────────────────────────────────────────────────────────────
const t = buildRules(BASE, { tenantId: TENANT });
check('tenant build: every `request.auth != null` is replaced', t.replaced === anyUser, `${t.replaced} vs ${anyUser}`);
check('tenant build: the only remaining `request.auth != null` is inside the helper',
  code(t.text).filter(l => /request\.auth\s*!=\s*null/.test(l)).length === 1);
check('tenant build: the helper checks the tenant id', t.text.includes(`request.auth.token.firebase.tenant == '${TENANT}'`));
check('tenant build: the helper is defined exactly once', (t.text.match(/function inThisWorkspace\(\)/g) || []).length === 1);

const lineOf = (text, re) => text.split('\n').find(l => re.test(l)) || '';
check('isAdmin() now also requires the workspace', /inThisWorkspace\(\)\s*$/.test(lineOf(t.text, /return inThisWorkspace\(\)\s*$/)) && t.text.includes('exists(/databases/$(database)/documents/admins/'));
const announceRead = t.text.split('\n').findIndex(l => /match \/announcements\//.test(l));
const announceBlock = t.text.split('\n').slice(announceRead, announceRead + 6).join('\n');
check('the known "any signed-in user" rule — announcements read — is now scoped', /allow read:\s*if inThisWorkspace\(\);/.test(announceBlock), announceBlock);
const invIdx = t.text.split('\n').findIndex(l => /match \/invites\//.test(l));
const invBlock = t.text.split('\n').slice(invIdx, invIdx + 8).join('\n');
check('the known "any signed-in user" rules — invites read AND update — are now scoped',
  /allow read:\s*if inThisWorkspace\(\);/.test(invBlock) && /allow update:\s*if inThisWorkspace\(\);/.test(invBlock), invBlock);

// ── default build ───────────────────────────────────────────────────────────
const d = buildRules(BASE, { tenantId: null });
check('default build: signed in AND no tenant (so a client\'s user cannot reach the default database)', d.text.includes("request.auth != null && !('tenant' in request.auth.token.firebase)"));
check('default build uses the same map-membership form the live isAdmin() already uses', BASE.includes("!('status' in callerAdmin())") && d.text.includes("!('tenant' in request.auth.token.firebase)"));
check('default build scopes the same number of checks', d.replaced === anyUser);

// ── nothing else changes ────────────────────────────────────────────────────
for (const [label, out] of [['tenant', t.text], ['default', d.text]]) {
  const cnt = (x, re) => (x.match(re) || []).length;
  check(`${label}: same number of allow statements (${cnt(BASE, /^\s*allow\s/gm)}) and match blocks (${cnt(BASE, /^\s*match\s/gm)})`,
    cnt(out, /^\s*allow\s/gm) === cnt(BASE, /^\s*allow\s/gm) && cnt(out, /^\s*match\s/gm) === cnt(BASE, /^\s*match\s/gm));
  // Remove the header + helper + substitutions: what is left must be the original, line for line.
  const normalized = out.split('\n').filter(l => !/GENERATED by|Edit firestore\.rules, not this|Added by scripts\/build-rules|True only for a user signed in/.test(l)).join('\n')
    .replace(/^\s*function inThisWorkspace\(\) \{\n\s*return [^\n]*\n\s*\}\n\n?/m, '').replace(/inThisWorkspace\(\)/g, 'request.auth != null').replace(/^\n+/, '');
  check(`${label}: undoing the substitutions gives back the original rules, character for character`, normalized === BASE.replace(/^\n+/, ''), (() => {
    const a = normalized.split('\n'), b = BASE.split('\n'); const i = a.findIndex((l, k) => l !== b[k]); return i < 0 ? 'length differs' : `first difference at line ${i + 1}:\n  got:      ${a[i]}\n  expected: ${b[i]}`; })());
  const commentsIn = BASE.split('\n').filter(l => /^\s*\/\//.test(l)), commentsOut = new Set(out.split('\n'));
  check(`${label}: every comment line in the original is preserved verbatim`, commentsIn.every(l => commentsOut.has(l)));
}

// ── a tenant id cannot inject rules ─────────────────────────────────────────
const evil = ["x'; allow read: if true; //", "abc d", "acme\n", "a'b'c'd", 'acme"x', 'acme\\x', '', 'ab', 'a'.repeat(65), "tenant-1') || true || ('", 'acme;', null && 'x'];
const accepted = evil.filter(v => v !== null && v !== undefined && !throws(() => buildRules(BASE, { tenantId: v })));
check(`${evil.filter(Boolean).length} hostile or malformed tenant ids are all rejected`, accepted.length === 0, accepted.join(' | '));
check('realistic tenant ids are accepted', ['acme-x1y2z', 'tenant2-m6tyz', 'ws_Beta-0001', 'A1B2C3D4'].every(v => !throws(() => buildRules(BASE, { tenantId: v }))));

// ── misuse is refused ───────────────────────────────────────────────────────
check('refuses to run on its own output (no double-scoping)', !!throws(() => buildRules(t.text, { tenantId: TENANT })));
check('refuses rules with no databases anchor', !!throws(() => buildRules('service cloud.firestore {}', { tenantId: TENANT })));
check('refuses rules with nothing to scope (wrong file)', !!throws(() => buildRules(BASE.replace(/request\.auth\s*!=\s*null/g, 'false'), { tenantId: TENANT })));
check('output is deterministic', buildRules(BASE, { tenantId: TENANT }).text === t.text);
check('different workspaces get different rules, differing only in the tenant id', (() => {
  const a = buildRules(BASE, { tenantId: 'aaaa-1111' }).text, b = buildRules(BASE, { tenantId: 'bbbb-2222' }).text;
  return a !== b && a.replace(/aaaa-1111/g, 'X') === b.replace(/bbbb-2222/g, 'X');
})());

// ── inline comments with `//` inside quotes are handled ─────────────────────
{
  const re = /(allow read:\s*if request\.auth != null;)/;
  const tricky = BASE.replace(re, '$1 // was `request.auth != null` for http://x');
  check('(test setup) the edit that adds a trailing comment really changed the rules', tricky !== BASE && re.test(BASE));
  const out = buildRules(tricky, { tenantId: TENANT }).text;
  const line = out.split('\n').find(l => l.includes('was `request.auth != null` for http://x')) || '';
  check('a trailing comment on a rule line is kept verbatim, while the rule itself is scoped', /allow read:\s*if inThisWorkspace\(\);\s*\/\/ was `request\.auth != null` for http:\/\/x$/.test(line), line);
}

console.log(`\n${passed} passed, ${failed} failed.`);
process.exit(failed ? 1 : 0);
